-- Generated by scripts/import_legacy_markdown.py.
-- Re-running this file is safe after migration/10-ricksu-bootstrap.sql.
SET NAMES utf8mb4;

INSERT INTO tb_category (id, category_name, create_time) VALUES
  (100, 'Tools & Tech', '2026-07-22 22:18:38'),
  (101, '论文写作', '2026-07-22 22:18:38')
ON DUPLICATE KEY UPDATE category_name = VALUES(category_name);

INSERT INTO tb_tag (id, tag_name, create_time) VALUES
  (100, '技术笔记', '2026-07-22 22:18:38'),
  (101, '论文写作', '2026-07-22 22:18:38'),
  (102, 'LaTeX', '2026-07-22 22:18:38'),
  (103, 'IEEE RAL', '2026-07-22 22:18:38')
ON DUPLICATE KEY UPDATE tag_name = VALUES(tag_name);

INSERT INTO tb_article
  (id, user_id, category_id, article_cover, article_title, article_content,
   create_time, update_time, is_top, is_draft, is_delete, permalink, summary)
VALUES
  (1001, 1, 100, '/legacy-assets/assets/images/background2.png', 'Tools & Tech', '# Tools & Tech

欢迎来到工具与技术部分！这里记录了我在日常工作和学习中使用的各种工具、技术和经验。

## 📚 内容导航

### 📝 论文写作
- [RAL 投稿经验](/articles/1004) - IEEE Robotics and Automation Letters 投稿指南

### 🔧 开发工具
（待添加更多内容）

### 💻 编程技术
（待添加更多内容）

### 🚀 部署运维
（待添加更多内容）

---

## 🎯 快速索引

| 类别 | 描述 | 链接 |
|------|------|------|
| 论文写作 | RAL 投稿经验与模板 | [查看](/articles/1004) |

---
论文查找网站：
https://papercopilot.com/
https://www.alphaxiv.org/
*持续更新中...*
', '2026-07-22 22:18:38', '2026-07-22 22:18:38', 0, 0, 0, 'tools-and-tech', '欢迎来到工具与技术部分！这里记录了我在日常工作和学习中使用的各种工具、技术和经验。'),
  (1002, 1, 101, '/legacy-assets/assets/images/background2.png', 'Latex使用教程', '# Latex使用教程
## 0.Overleaf 使用教程
[30分钟学会Overleaf](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes)
', '2026-07-22 22:18:38', '2026-07-22 22:18:38', 0, 0, 0, 'latex-guide', '30分钟学会Overleaf'),
  (1003, 1, 101, '/legacy-assets/assets/images/background2.png', '如何进行论文写作', '# 如何进行论文写作
参考内容：
1.[GAMES](https://pengsida.net/games003/)
2.[彭思达科研经验分享](https://github.com/pengsida/learning_research)', '2026-07-22 22:18:38', '2026-07-22 22:18:38', 0, 0, 0, 'paper-writing', '参考内容：'),
  (1004, 1, 101, '/legacy-assets/assets/images/background2.png', 'RAL 投稿经验', '# RAL 投稿经验
## 0.模板下载
### 匿名模板
1.进入ieee[官方网站](https://ieeeauthorcenter.ieee.org/)
![图片](/legacy-assets/Tools%20%26%20Tech/paper_writing/images/RAL/4.png)
### 终稿模板
1.进入ieee[作者中心](https://ieeeauthorcenter.ieee.org/)，点击AUTHOR TOOLs（作者工具）
![图片](/legacy-assets/Tools%20%26%20Tech/paper_writing/images/RAL/1.png)
2.进入作者工具网站：Author Tools - IEEE Author Center New Authors，点击链接：IEEE Template Selector去选择模板
![图片](/legacy-assets/Tools%20%26%20Tech/paper_writing/images/RAL/2.png)
3.进入作者模板选择：依次进行选择，这里依次选择Transactions,journals and letters，输入期刊名称：IEEE Robotics and Automation Letters
选择文章类型;
选择文章写作格式;
最后点击下载即可.
![图片](/legacy-assets/Tools%20%26%20Tech/paper_writing/images/RAL/3.png)
', '2026-07-22 22:18:38', '2026-07-22 22:18:38', 0, 0, 0, 'ieee-ral-submission', '1.进入ieee官方网站')
ON DUPLICATE KEY UPDATE
  category_id = VALUES(category_id),
  article_cover = VALUES(article_cover),
  article_title = VALUES(article_title),
  article_content = VALUES(article_content),
  update_time = VALUES(update_time),
  permalink = VALUES(permalink),
  summary = VALUES(summary);

DELETE FROM tb_article_tag WHERE article_id BETWEEN 1001 AND 1004;
INSERT INTO tb_article_tag (id, article_id, tag_id) VALUES
  (10001, 1001, 100),
  (10002, 1002, 101),
  (10003, 1002, 102),
  (10004, 1003, 101),
  (10005, 1004, 101),
  (10006, 1004, 103);
