#!/usr/bin/env python3
"""Build the FishBlog SQL import for the preserved MkDocs articles."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "legacy-content" / "docs"
OUTPUT = ROOT / "migration" / "20-legacy-articles.sql"


@dataclass(frozen=True)
class Article:
    article_id: int
    source: str
    permalink: str
    category_id: int
    tag_ids: tuple[int, ...]


ARTICLES = (
    Article(1001, "Tools & Tech/Tools & Tech.md", "tools-and-tech", 100, (100,)),
    Article(
        1002,
        "Tools & Tech/paper_writing/Latex.md",
        "latex-guide",
        101,
        (101, 102),
    ),
    Article(
        1003,
        "Tools & Tech/paper_writing/PaperWriting.md",
        "paper-writing",
        101,
        (101,),
    ),
    Article(
        1004,
        "Tools & Tech/paper_writing/RAL.md",
        "ieee-ral-submission",
        101,
        (101, 103),
    ),
)

ARTICLE_BY_PATH = {article.source: article for article in ARTICLES}


def sql(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def title_of(markdown: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+?)\s*$", markdown, flags=re.MULTILINE)
    return match.group(1).strip() if match else fallback


def summary_of(markdown: str) -> str:
    for raw_line in markdown.splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "---", "![", "|")):
            continue
        line = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", line)
        line = re.sub(r"[*_`>]", "", line)
        return line[:240]
    return "RickSu 的技术与研究笔记"


def public_url(path: Path) -> str:
    relative = path.resolve().relative_to(DOCS.resolve())
    return "/legacy-assets/" + quote(relative.as_posix(), safe="/")


def rewrite_markdown(markdown: str, source_path: Path) -> str:
    def replace_image(match: re.Match[str]) -> str:
        alt, target = match.group(1), match.group(2).strip()
        if re.match(r"^(?:https?:|data:|/)", target):
            return match.group(0)
        resolved = (source_path.parent / target).resolve()
        return f"![{alt}]({public_url(resolved)})"

    def replace_link(match: re.Match[str]) -> str:
        label, target = match.group(1), match.group(2).strip()
        if not target.lower().endswith(".md"):
            return match.group(0)
        resolved = (source_path.parent / target).resolve()
        relative = resolved.relative_to(DOCS.resolve()).as_posix()
        article = ARTICLE_BY_PATH.get(relative)
        return f"[{label}](/articles/{article.article_id})" if article else match.group(0)

    markdown = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", replace_image, markdown)
    markdown = re.sub(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)", replace_link, markdown)

    # Repair one malformed legacy link in the source material without changing
    # the archival copy under legacy-content/.
    return markdown.replace(
        "[彭思达科研经验分享]([text](https://github.com/pengsida/learning_research))",
        "[彭思达科研经验分享](https://github.com/pengsida/learning_research)",
    )


def main() -> None:
    created_at = datetime.fromtimestamp(
        min((DOCS / article.source).stat().st_mtime for article in ARTICLES)
    ).strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "-- Generated by scripts/import_legacy_markdown.py.",
        "-- Re-running this file is safe after migration/10-ricksu-bootstrap.sql.",
        "SET NAMES utf8mb4;",
        "",
        "INSERT INTO tb_category (id, category_name, create_time) VALUES",
        f"  (100, 'Tools & Tech', '{created_at}'),",
        f"  (101, '论文写作', '{created_at}')",
        "ON DUPLICATE KEY UPDATE category_name = VALUES(category_name);",
        "",
        "INSERT INTO tb_tag (id, tag_name, create_time) VALUES",
        f"  (100, '技术笔记', '{created_at}'),",
        f"  (101, '论文写作', '{created_at}'),",
        f"  (102, 'LaTeX', '{created_at}'),",
        f"  (103, 'IEEE RAL', '{created_at}')",
        "ON DUPLICATE KEY UPDATE tag_name = VALUES(tag_name);",
        "",
    ]

    article_values: list[str] = []
    article_tag_values: list[str] = []
    relation_id = 10001

    for article in ARTICLES:
        source_path = DOCS / article.source
        markdown = rewrite_markdown(source_path.read_text(encoding="utf-8"), source_path)
        title = title_of(markdown, source_path.stem)
        summary = summary_of(markdown)
        modified = datetime.fromtimestamp(source_path.stat().st_mtime).strftime(
            "%Y-%m-%d %H:%M:%S"
        )
        article_values.append(
            "  "
            + "("
            + ", ".join(
                (
                    str(article.article_id),
                    "1",
                    str(article.category_id),
                    "'/legacy-assets/assets/images/background2.png'",
                    f"'{sql(title)}'",
                    f"'{sql(markdown)}'",
                    f"'{modified}'",
                    f"'{modified}'",
                    "0",
                    "0",
                    "0",
                    f"'{article.permalink}'",
                    f"'{sql(summary)}'",
                )
            )
            + ")"
        )
        for tag_id in article.tag_ids:
            article_tag_values.append(
                f"  ({relation_id}, {article.article_id}, {tag_id})"
            )
            relation_id += 1

    lines.extend(
        (
            "INSERT INTO tb_article",
            "  (id, user_id, category_id, article_cover, article_title, article_content,",
            "   create_time, update_time, is_top, is_draft, is_delete, permalink, summary)",
            "VALUES",
            ",\n".join(article_values),
            "ON DUPLICATE KEY UPDATE",
            "  category_id = VALUES(category_id),",
            "  article_cover = VALUES(article_cover),",
            "  article_title = VALUES(article_title),",
            "  article_content = VALUES(article_content),",
            "  update_time = VALUES(update_time),",
            "  permalink = VALUES(permalink),",
            "  summary = VALUES(summary);",
            "",
            "DELETE FROM tb_article_tag WHERE article_id BETWEEN 1001 AND 1004;",
            "INSERT INTO tb_article_tag (id, article_id, tag_id) VALUES",
            ",\n".join(article_tag_values) + ";",
            "",
        )
    )
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(ARTICLES)} articles")


if __name__ == "__main__":
    main()
